domain: openshift.io

clusters: []

# Platform
machinesets:
  chartVersion: 1.0.0

system_roles:
  chartVersion: 1.0.0

acm:
  chartVersion: 1.0.1
  enabled: false
  enableCapacity: true

ansiblerunner:
  chartVersion: 1.0.1

nfd:
  enabled: false 
  chartVersion: 1.0.0

nvidiagpu:
  enabled: false 
  chartVersion: 1.0.0

# GitOps
gitops:
  namespace: openshift-gitops
  channel: gitops-1.19
  updater:
    chartVersion: 1.0.0
    enabled: false

chains:
  enabled: false

tekton:
  chartVersion: 1.0.0
  enabled: false
  enableCapacity: false

# Secrets Management
certmanager:
  chartVersion: 1.0.0
  enabled: true

external_secrets:
  chartVersion: 1.0.0
  enabled: true
  namespace: external-secrets
  connectors:
    chartVersion: 1.0.0
  k8sConnector:
    enabled: true

vault:
  chartVersion: 0.31.0
  enabled: true
  appVersion: 1.21
  address: "http://vault-service.vault-server.svc.cluster.local:8200"

# Identity Management
keycloak:
  chartVersion: 1.0.0
  enabled: false

usersync:
  chartVersion: 1.0.0

# Artifacts
gitea:
  chartVersion: 1.0.0
  enabled: true
  namespace: gitea

gitlab:
  chartVersion: 1.0.0
  enabled: true
  namespace: gitlab-system
  runners: 
    enabled: false

gitlab_repo_creds:
  chartVersion: 1.0.0

gitlab_runner:
  chartVersion: 1.0.0

minio:
  enabled: false
  chartVersion: 1.0.0

npm:
  enabled: true
  chartVersion: 4.29.0

opentelemetry:
  chartVersion: 1.0.0
  enabled: false

quay:
  enabled: false
  chartVersion: 1.0.0
  enableCapacity: true

quay_bridge:
  enabled: false
  chartVersion: 1.0.0

registry:
  enabled: false

# Message Brokers
amq:
  enabled: false
  chartVersion: 1.0.0
  enableCapacity: false
  count: 1
  sku: Standard_D8s_v3

# AI Requirements
authorino:
  enabled: false
  chartVersion: 1.0.0

kiali:
  enabled: false
  chartVersion: 1.0.0

rhoai:
  enabled: false
  chartVersion: 1.0.0
  enableCapacity: true

serverless:
  enabled: false
  chartVersion: 1.0.0

servicemesh:
  enabled: false
  chartVersion: 1.0.0

tracing:
  enabled: false
  chartVersion: 1.0.0

# Developer Experience
acs:
  chartVersion: 1.0.0
  enabled: false
  enableCapacity: true

devhub:
  chartVersion: 1.0.1
  enabled: false
  helm:
    enabled: false
    chartVersion: 1.0.0

devspaces:
  chartVersion: 1.0.0
  enabled: false
  enableCapacity: false
  count: 1
  sku: Standard_D8s_v3

gatekeeper:
  chartVersion: 1.0.0
  enabled: false

rhtas:
  chartVersion: 1.0.0
  namespace: rhtas
  enabled: false

sonarqube:
  chartVersion: ~8
  enabled: false
