{{ if hasKey .Values "acm" }}
{{ if .Values.acm.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "acm-plugin"
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: "{{ .Values.acm.namespace }}"
    server: 'https://kubernetes.default.svc'
  source:
    chart: acm
    repoURL: "https://na-launch-workshop.github.io/platform-charts"
    targetRevision: "{{ .Values.acm.chartVersion }}"
    helm:
      valuesObject: {{ toJson .Values }}
  project: system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{- end }}
{{ end }}