{{- if .Values.gitea.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: gitea-token
  data:
  - secretKey: GITEA_TOKEN
    remoteRef:
      key: gitea
      property: group_access_token
{{- end }}
