apiVersion: batch/v1
kind: CronJob
metadata:
  name: "user-sync-cronjob"
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "user-sync-job"
              image: "quay.io/na-east-launch/user-sync:latest"
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: keycloak-credentials
                - secretRef:
                    name: gitlab-credentials
              env:
                - name: DOMAIN  
                  value: "{{ .Values.domain }}"
                - name: GITLAB_USERNAME
                  value: "root"
          restartPolicy: Never
