{{- if .Values.gitlab.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: gitea-plugin
data:
  gitea-plugin.yaml: |
    integrations:
      gitea:
        - host: gitea.{{ .Values.host }}
          password: ${GITEA_TOKEN}

{{- end }}
