domain: openshift.api

services:
  chartVersion: 1.0.0

machinesets:
  chartVersion: 1.0.0
  enabled: true
  helmValues:
    machineset: 
      enabled: true
    machinesets:
      - name: acs
        machine_type: Standard_D8s_v3
 
registry:
  enabled: false

acs:
  chartVersion: 1.0.0
  enabled: true

acm:
  chartVersion: 1.0.0
  enabled: false

keycloak:
  chartVersion: 1.0.0
  enabled: true

gatekeeper:
  chartVersion: 1.0.0
  enabled: true

gitops:
  namespace: openshift-gitops
  channel: gitops-1.19
  updater:
    chartVersion: 1.0.0
    enabled: true

tekton:
  chartVersion: 1.0.0
  enabled: false

sonarqube:
  chartVersion: ~8
  enabled: true

devhub:
  chartVersion: 1.0.1
  enabled: true

rhtas:
  chartVersion: 1.0.0
  namespace: rhtas
  enabled: false

gitea:
  chartVersion: 1.0.0
  enabled: true
  namespace: gitea

gitlab:
  chartVersion: 1.0.0
  enabled: true
  namespace: gitlab-system

external_secrets:
  enabled: true
  chartVersion: 1.0.0
  namespace: external-secrets

vault:
  chartVersion: 0.31.0
  enabled: true
