host: "api.openshift.io"

backend:
  postgres:
    enabled: true
  sqlite3:
    enabled: false

gitea:
  enabled: false

gitlab:
  enabled: false

github:
  enabled: false

postgres:
  storageClassName: lvms-local

catalogs:
### Templates to deploy OpenShift AI ecosystem
#  - https://github.com/na-launch-workshop/platform-software-templates/blob/main/catalogs/templates.yaml
### Templates to deploy Launch workshop
  - https://github.com/na-launch-workshop/platform-software-templates/blob/main/workshop/templates.yaml

clusters: []
