domain: openshift.api

## Current Default Rollout-Controller
controller:
  name: infrastructure
  chartVersion: 1.0.0

system_roles:
  chartVersion: 1.0.0

# GitOps
gitops:
  namespace: openshift-gitops
  channel: gitops-1.14
  enabled: false
  updater:
    chartVersion: 1.0.0
    enabled: false

# Secrets Management
external_secrets:
  enabled: false
  chartVersion: 1.0.0
  namespace: external-secrets
  connectors:
    chartVersion: 1.0.0
  k8sConnector:
    enabled: true

vault:
  chartVersion: 0.31.0
  enabled: false
  address: "http://vault-service.vault-server.svc.cluster.local:8200"

# Identity Management
keycloak:
  chartVersion: 1.0.0
  enabled: false

# Artifacts
quay:
  chartVersion: 1.0.0
  enabled: false

npm:
  enabled: true
  chartVersion: 4.26.1

minio:
  enabled: false
  chartVersion: 1.0.0

opentelemetry:
  chartVersion: 1.0.0
  enabled: false

gitlab:
  namespace: gitlab-system
  chartVersion: 1.0.0
  enabled: true
  runners: 
    enabled: false

# Message Brokers
amq:
  enabled: false
  chartVersion: 1.0.0

# AI Requirements
authorino:
  enabled: false
  chartVersion: 1.0.0

kiali:
  enabled: false
  chartVersion: 1.0.0

tracing:
  enabled: false
  chartVersion: 1.0.0

serverless:
  enabled: false
  chartVersion: 1.0.0

servicemesh:
  enabled: false
  chartVersion: 1.0.0

rhoai:
  enabled: false
  chartVersion: 1.0.0

# Developer Experience
devhub:
  chartVersion: 1.0.0
  enabled: false
  helm:
    enabled: false
    chartVersion: 1.0.0

devspaces:
  chartVersion: 1.0.0
  enabled: false
