apiVersion: v1
data:
  _generals_: ""
  actions: RU5BQkxFRCA9IHRydWUK
  cache: QURBUFRFUj1yZWRpcwpIT1NUPXJlZGlzOi8vOmNoYW5nZW1lQGdpdGVhLXNlcnZpY2UtdmFsa2V5LWhlYWRsZXNzLmdpdGVhLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkvMD9wb29sX3NpemU9MTAwJmlkbGVfdGltZW91dD0xODBzJgo=
  database: REJfVFlQRT1wb3N0Z3JlcwpIT1NUPWdpdGVhLXNlcnZpY2UtcG9zdGdyZXNxbC5naXRlYS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyCk5BTUU9Z2l0ZWEKUEFTU1dEPWdpdGVhClVTRVI9Z2l0ZWEK
  indexer: SVNTVUVfSU5ERVhFUl9UWVBFPWJsZXZlClJFUE9fSU5ERVhFUl9FTkFCTEVEPXRydWU=
  metrics: RU5BQkxFRD1mYWxzZQ==
  migrations: QUxMT1dFRF9ET01BSU5TID0gZ2l0aHViLmNvbSwgYXBpLmdpdGh1Yi5jb20K
  oauth2_client: RU5BQkxFX0FVVE9fUkVHSVNUUkFUSU9OID0gdHJ1ZQo=
  queue: Q09OTl9TVFI9cmVkaXM6Ly86Y2hhbmdlbWVAZ2l0ZWEtc2VydmljZS12YWxrZXktaGVhZGxlc3MuZ2l0ZWEuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OS8wP3Bvb2xfc2l6ZT0xMDAmaWRsZV90aW1lb3V0PTE4MHMmClRZUEU9cmVkaXMK
  repository: Uk9PVD0vZGF0YS9naXQvZ2l0ZWEtcmVwb3NpdG9yaWVz
  security: SU5TVEFMTF9MT0NLPXRydWU=
  server: {{ tpl (.Files.Get "config/gitea.server.config") . | b64enc }}
  session: UFJPVklERVI9cmVkaXMKUFJPVklERVJfQ09ORklHPXJlZGlzOi8vOmNoYW5nZW1lQGdpdGVhLXNlcnZpY2UtdmFsa2V5LWhlYWRsZXNzLmdpdGVhLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkvMD9wb29sX3NpemU9MTAwJmlkbGVfdGltZW91dD0xODBzJgo=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: gitea
    meta.helm.sh/release-namespace: gitea
  labels:
    app: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gitea
    app.kubernetes.io/version: 1.24.6
    helm.sh/chart: gitea-12.4.0
    version: 1.24.6
  name: gitea-service-inline-config
type: Opaque
