apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gitea-charts
    repo: https://dl.gitea.io/charts/
    version: 12.4.0
    releaseName: gitea
    namespace: "{{ .Values.namespace }}"
    valuesFile: values.yaml
