apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "gitea-system-secret-priming"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: eso-admin-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: "gitea-group-access-pat"
  data:
    - match:
        secretKey: "GITEA_TOKEN"
        remoteRef:
          remoteKey: "gitea"
          property: "token"
