apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gitea-repo-org-credentials
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: gitea-repo-org-credentials
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: "repo-creds"
      data:
        password: "{{`{{ .password }}`}}"
        username: "gitea_admin"
        url: "https://gitea.{{ .Values.domain }}/workshop"
  data:
    - secretKey: "password"
      remoteRef:
        key: gitea
        property: token
